# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


channels:
  - conda-forge
  - nvidia
  - nvidia/label/dev # Required for the morpheus-llm package alpha packages. Will be overridden when released
  - rapidsai
  - huggingface
dependencies:
  - aiohttp-client-cache=0.11
  - aiohttp=3.9
  - aioresponses=0.7.6
  - beautifulsoup4=4.12
  - esprima-python=4.0 # Required to parse JavaScript code
  # - faiss-gpu=1.7 # Uncomment this when the package supports CUDA 12. See: https://github.com/conda-forge/faiss-split-feedstock/pull/72
  - faiss=1.7
  - gitpython=3.1
  - httpx>=0.23,<0.28 # work-around for https://github.com/openai/openai-python/issues/1915
  - json5=0.9
  - morpheus-llm=24.10
    # cuda-python=12.6.1 cannot be used because of -
    # https://github.com/NVIDIA/cuda-python/issues/215
    # NOTE: cuda-python is being downloaded some times from the nvidia channel and
    # sometimes from conda-forge. cuda-python can be dropped from this list of
    # dependencies after 12.6.2 is available on both channels.
  - cuda-python!=12.6.1
  - openai=1.13
  - packaging>=23.2,<24.0  # versions required by langchain-core
  - pydantic=2.6
  - python>=3.10.15,<3.11
  - tenacity>=8.1.0,<9.0.0  # versions required by langchain
  - tiktoken>=0.3.2,<0.6.0
  - transformers
  - uvloop

  ####### Pip Transitive Dependencies (keep sorted!) #######
  # These are dependencies that are available on conda, but are required by the pip packages listed below. Its much
  # better to install them with conda than pip to allow for better dependency resolution.
  - huggingface_hub>=0.23.2,<1.0  # required by langchain-community > sentence-transformers > transformers

  ####### Pip Dependencies (keep sorted!) #######
  - pip
  - pip:
    - google-search-results==2.4
    # Some of the langchain packages are available in conda but cause the solver to fail
    - langchain==0.2.16
    - langchain-community==0.2.17
    - langchain-core==0.2.41
    - langchain-nvidia-ai-endpoints==0.2.0
    - nemollm
    - pydpkg==1.9.2
    - rank_bm25==0.2.2
    # The conda version of sentence-transformers installs CPU-only versions of torch packages
    - sentence-transformers==2.7
    # The tree-sitter packages are langchain transitive dependencies for parsing other code languages.
    # The conda version is missing library files https://github.com/conda-forge/tree_sitter_languages-feedstock/issues/9
    - tree-sitter==0.21.3
    - tree-sitter-languages==1.10.2
    - univers==30.12  # Required for dependency version comparison
